FROM golang
ADD . /go/src/github.com/nikogura/redisproxy
WORKDIR /go/src/github.com/nikogura/redisproxy
RUN go get github.com/kardianos/govendor
RUN govendor sync
RUN go test -v ./...
RUN go install
RUN DEBIAN_FRONTEND=noninteractive apt-get -qq update
RUN DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends -y redis-tools
ENV SIZE __SIZE__
ENV EXPIRATION __EXPIRATION__
ENV PORT __PORT__
ENV REDIS __REDIS__
CMD ["./run.sh"]
